version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/monitoring/codedeploy-bundle
permissions:
  - object: /home/ubuntu/monitoring/codedeploy-bundle/deploy-scripts
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  ApplicationStop:
    - location: deploy-scripts/stop_stack.sh
      timeout: 180
      runas: ubuntu
  AfterInstall:
    - location: deploy-scripts/deploy_stack.sh
      timeout: 900
      runas: ubuntu
  ValidateService:
    - location: deploy-scripts/validate_stack.sh
      timeout: 180
      runas: ubuntu
